package taxapi

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"time"
)

// maxPriceSeriesRange bounds a single /price-series request. Callers wanting
// more history page with repeated start/end-bounded requests instead of one
// unbounded pull (each day not already cached in the Oracle is a live call).
const maxPriceSeriesRange = 730 * 24 * time.Hour

// pricePoint is one day's published reference price for a denom.
type pricePoint struct {
	Date  string  `json:"date"`
	USD   float64 `json:"usd"`
	Found bool    `json:"found"` // false = no price published for this day (see Methodology)
}

// handlePriceSeries publishes the daily USD price series for a denom (ATOM by
// default) over the requested range, generated by calling the exact same
// Oracle.PriceAt pipeline every tax report uses — this is not a separate
// calculation, so it can never drift from what a report actually charged a
// given day (INF-203).
func (s *Server) handlePriceSeries(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	chain := def(q.Get("chain"), "mainnet")
	denom := def(q.Get("denom"), s.native.Denom)
	end := dateParam(q.Get("end"), nowUTC())
	start := dateParam(q.Get("start"), end.AddDate(0, 0, -90))

	if end.Before(start) {
		http.Error(w, "end must be on or after start", http.StatusBadRequest)
		return
	}
	if end.Sub(start) > maxPriceSeriesRange {
		http.Error(w, fmt.Sprintf("range too large (max %d days per request); narrow start/end and page through history", int(maxPriceSeriesRange.Hours()/24)), http.StatusBadRequest)
		return
	}

	points := make([]pricePoint, 0, int(end.Sub(start).Hours()/24)+1)
	for d := start; !d.After(end); d = d.AddDate(0, 0, 1) {
		dateStr := d.Format("2006-01-02")
		usd, found := s.oracle.PriceAt(chain, denom, dateStr)
		points = append(points, pricePoint{Date: dateStr, USD: usd, Found: found})
	}

	if def(q.Get("format"), "json") == "csv" {
		w.Header().Set("Content-Type", "text/csv")
		w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%s-price-series.csv", denom))
		cw := csv.NewWriter(w)
		_ = cw.Write([]string{"date", "denom", "usd", "found", "methodology_version"})
		for _, p := range points {
			usdStr := ""
			if p.Found {
				usdStr = strconv.FormatFloat(p.USD, 'f', -1, 64)
			}
			_ = cw.Write([]string{p.Date, denom, usdStr, boolStr(p.Found), MethodologyVersion})
		}
		cw.Flush()
		return
	}

	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(map[string]any{
		"chain":               chain,
		"denom":               denom,
		"methodology_version": MethodologyVersion,
		"points":              points,
	})
}

func (s *Server) handleMethodology(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(currentMethodology())
}
